spring:
  application:
    name: intelliheart-backend
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8080
  servlet:
    context-path: /

# Конфигурация ML микросервиса
ml:
  service:
    url: http://localhost:8000

logging:
  level:
    root: INFO
    com.damumed.intelliheart: DEBUG
